Repository nextcloud/news, pull requests merged in 2018-10, with the labels that each got.

#283 Entity setters + getters
  lib/Db/Feed.php
  lib/Db/Folder.php
  lib/Db/Item.php
  lib/Service/FeedService.php
  lib/Utility/OPMLExporter.php
  tests/Integration/Fixtures/FeedFixture.php
  tests/Integration/Fixtures/FolderFixture.php
  tests/Integration/Fixtures/ItemFixture.php
  tests/Unit/Controller/EntityApiSerializerTest.php
  tests/Unit/Controller/ExportControllerTest.php
  tests/Unit/Controller/ItemApiControllerTest.php
  tests/Unit/Db/FeedTest.php
  tests/Unit/Db/FolderMapperTest.php
  tests/Unit/Service/FeedServiceTest.php
  tests/Unit/Utility/OPMLExporterTest.php
Labels: 3. to review, enhancement

#338 Feature: make compact mode headers sticky
  css/content.css
Labels: 3. to review, design, enhancement

#348 13.0.2 & changelog
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#364 Npm bump
  composer.json
  composer.lock
  js/package-lock.json
  js/package.json
Labels: 3. to review

#365 13.0.3
  appinfo/info.xml
Labels: 3. to review
