Repository nextcloud/news, pull requests merged in 2018-09, with the labels that each got.

#319 Compact mode scroll fix + nc14 last patch
  css/app.css
  js/directive/NewsScroll.js
Labels: 3. to review, bug, high, regression

#332 Update CHANGELOG.md
  CHANGELOG.md
Labels: 3. to review, enhancement

#334 Fix firefox wide screen and mobile view
  css/content.css
  css/mobile.css
Labels: 3. to review, bug, design

#335 13.0.1
  appinfo/info.xml
  js/package-lock.json
  js/package.json
Labels: 3. to review

#328 Restore a working User-Agent
  lib/AppInfo/Application.php
Labels: 3. to review, bug, needs info
