Repository nextcloud/news, pull requests merged in 2019-03, with the labels that each got.

#434 No background on active item
  css/content.css
Labels: design, in progress, low, undecided

#441 fix search
  js/directive/NewsSearch.js
Labels: 3. to review

#428 fix/allow CDATA encoding
  AUTHORS.md
  appinfo/register_command.php
  composer.json
  composer.lock
  lib/AppInfo/Application.php
  lib/Command/ShowFeed.php
  lib/Config/FetcherConfig.php
  lib/Db/Item.php
  lib/Fetcher/FeedFetcher.php
  lib/Utility/ProxyConfigParser.php
  tests/Unit/Fetcher/FeedFetcherTest.php
  tests/Unit/Utility/ProxyConfigParserTest.php
Labels: high, in progress

#439 Update the Changelog
  CHANGELOG.md
Labels: in progress

#462 Release 13.1.4
  CHANGELOG.md
  appinfo/info.xml
  js/package-lock.json
  js/package.json
Labels: 4. to release
