Repository nextcloud/news, pull requests merged in 2020-12, with the labels that each got.

#969 fix xDebug 3.0
  Makefile
Labels: Skip-Changelog

#974 update frontend test badge
  README.md
Labels: Skip-Changelog

#978 Don't suggest to make issues for features.
  CONTRIBUTING.md
Labels: Skip-Changelog

#986 Update README.md
  docs/faq/README.md
Labels: Skip-Changelog, documentation

#987 Features should not be requested anymore via an issue
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Skip-Changelog, documentation

#975 Remove LastModified-based cursor when updating feeds
  CHANGELOG.md
  lib/Db/NewsMapperV2.php
  lib/Fetcher/FeedFetcher.php
  lib/Service/ItemServiceV2.php
  tests/Unit/Fetcher/FeedFetcherTest.php
Labels: API

#989 Remove unnecesary if clause
  .github/workflows/php-tests.yml
Labels: Skip-Changelog

#999 update dependabot labels
  .github/dependabot.yml
Labels: Skip-Changelog

#994 Release 15.1.1-rc2
  AUTHORS.md
  CHANGELOG.md
  appinfo/info.xml
  composer.lock
Labels: 3. to review

#1006 Release 15.1.1
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#1004 Remove PHPunit integration tests
  .github/workflows/integration-tests.yml
  CHANGELOG.md
  Makefile
  phpunit.integration.xml
  tests/Integration/Db/FeedMapperTest.php
  tests/Integration/Db/ItemMapperTest.php
  tests/Integration/Fixtures/FeedFixture.php
  tests/Integration/Fixtures/Fixture.php
  tests/Integration/Fixtures/FolderFixture.php
  tests/Integration/Fixtures/ItemFixture.php
  tests/Integration/Fixtures/data/default.php
  tests/Integration/Fixtures/data/readitem.php
  tests/Integration/IntegrationTest.php
Labels: API
