Repository nextcloud/news, pull requests merged in 2020-04, with the labels that each got.

#627 Nc19
  .travis.yml
  AUTHORS.md
  CHANGELOG.md
  appinfo/info.xml
  composer.lock
  js/package-lock.json
  js/package.json
Labels: 3. to review

#669 Release 14.1.4
  CHANGELOG.md
Labels: 3. to review, 4. to release

#675 Release 14.1.5
  AUTHORS.md
  CHANGELOG.md
  js/package-lock.json
  js/package.json
Labels: 3. to review, 4. to release

#684 If modified since
  lib/Fetcher/Client/FeedIoClient.php
  lib/Fetcher/Client/LegacyGuzzleClient.php
  lib/Fetcher/Client/LegacyGuzzleResponse.php
Labels: 2. developing, bug

#685 Release 14.1.6
  AUTHORS.md
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, 4. to release
