Repository nextcloud/news, pull requests merged in 2020-02, with the labels that each got.

#626 Release 14.1.3
  CHANGELOG.md
  appinfo/info.xml
  composer.lock
Labels: 4. to release

#599 Basic Media-RSS support
  appinfo/database.xml
  docs/plugins/README.md
  lib/Db/Item.php
  lib/Fetcher/FeedFetcher.php
  templates/part.content.php
  tests/Integration/Fixtures/ItemFixture.php
  tests/Unit/Controller/ExportControllerTest.php
  tests/Unit/Db/ItemTest.php
Labels: 3. to review, 4. to release

#636 Don't install symfony/console via composer
  composer.json
  composer.lock
Labels: 3. to review, bug
