Repository nextcloud/news, pull requests merged in 2021-03, with the labels that each got.

#1224 Switch to sha1 for more security
  .github/workflows/build-release.yml
Labels: Skip-Changelog

#955 Make PHPstan stricter
  CHANGELOG.md
  composer.json
  composer.lock
  lib/Command/Config/FeedAdd.php
  lib/Config/FetcherConfig.php
  lib/Config/LegacyConfig.php
  lib/Controller/FeedApiController.php
  lib/Controller/FeedController.php
  lib/Controller/FolderApiController.php
  lib/Controller/FolderController.php
  lib/Cron/UpdaterJob.php
  lib/Db/EntityJSONSerializer.php
  lib/Db/Item.php
  lib/Db/ItemMapperV2.php
  lib/Fetcher/Client/FeedIoClient.php
  lib/Fetcher/FeedFetcher.php
  lib/Service/Exceptions/ServiceException.php
  lib/Service/FeedServiceV2.php
  lib/Service/ImportService.php
  lib/Service/ItemServiceV2.php
  lib/Service/StatusService.php
Labels: 2. developing, API, enhancement

#1215 Search: Add folder search
  CHANGELOG.md
  lib/AppInfo/Application.php
  lib/Search/FolderSearchProvider.php
Labels: API, enhancement

#1214 DB: Updates should use set()
  CHANGELOG.md
  appinfo/info.xml
  lib/Command/Debug/FeedRead.php
  lib/Command/Debug/FolderRead.php
  lib/Command/Debug/ItemRead.php
  lib/Db/FeedMapperV2.php
  lib/Db/FolderMapperV2.php
  lib/Db/ItemMapperV2.php
  lib/Service/FeedServiceV2.php
  lib/Service/FolderServiceV2.php
  lib/Service/ItemServiceV2.php
  tests/Unit/Db/FeedMapperTest.php
  tests/Unit/Db/FolderMapperTest.php
  tests/Unit/Db/ItemMapperAfterTest.php
  tests/Unit/Db/ItemMapperPaginatedTest.php
  tests/Unit/Db/ItemMapperTest.php
  tests/Unit/Db/MapperTestUtility.php
  tests/integration/feeds.bats
  tests/integration/folders.bats
Labels: API, bug, patch
