Repository nextcloud/news, pull requests merged in 2021-01, with the labels that each got.

#907 Add psalm for static code analysis
  .github/workflows/static-code-check.yml
  composer.json
  composer.lock
  psalm.xml
Labels: 3. to review, API, Skip-Changelog

#1025 update nc version in actions
  .github/workflows/frontend-tests.yml
  .github/workflows/integration-tests.yml
  .github/workflows/php-tests.yml
Labels: API, Skip-Changelog

#1032 Test release drafter for preparing releases
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: Skip-Changelog, enhancement

#1036 fix changelog and version
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#1037 first improvements for the release-drafter
  .github/release-drafter.yml
Labels: Skip-Changelog

#1041 fix opened state of folders is not restored
  CHANGELOG.md
  lib/Db/Folder.php
  tests/Unit/Db/FolderTest.php
Labels: bug

#1045 fix TypeError in ItemMapper
  CHANGELOG.md
  lib/Db/ItemMapper.php
Labels: bug

#1048 fix typo in release-drafter config
  .github/release-drafter.yml
Labels: Skip-Changelog

#1051 link to the issue template chooser instead of creating an empty one
  templates/part.settings.php
Labels: Skip-Changelog, patch

#1052 Lead users to Discussions
  .github/ISSUE_TEMPLATE/config.yml
Labels: 2. developing, Skip-Changelog

#1060 CI: Bump actions versions and improve statics name
  .github/workflows/php-tests.yml
  .github/workflows/static-code-check.yml
Labels: Skip-Changelog

#1062 remove alternating row colors and increase row height
  CHANGELOG.md
  css/content.css
Labels: enhancement

#1066 Release environment
  .github/workflows/build-release.yml
Labels: 3. to review, Skip-Changelog, patch

#1068 add dependency checks for Github actions
  .github/dependabot.yml
Labels: Skip-Changelog

#1070 ignore current issues but catch new ones
  psalm.xml
  tests/psalm-baseline.xml
Labels: Skip-Changelog, patch

#1078 update the contributing file
  CONTRIBUTING.md
Labels: Skip-Changelog, patch

#1065 Mappers: Implement item purging
  CHANGELOG.md
  lib/Command/Updater/AfterUpdate.php
  lib/Db/ItemMapperV2.php
  lib/Service/ItemServiceV2.php
  tests/Unit/Command/AfterUpdateTest.php
Labels: 2. developing, API, patch
