Repository nextcloud/news, pull requests merged in 2021-05, with the labels that each got.

#1319 Fix some of the favicon errors
  CHANGELOG.md
  composer.lock
  lib/Fetcher/FeedFetcher.php
  tests/integration/feeds.bats
  tests/integration/helpers/settings.bash
Labels: backport-request, bug, patch

#1332 revert composer change
  composer.lock
Labels: Skip-Changelog

#1333 Require 64 bit integer
  CHANGELOG.md
  appinfo/info.xml
Labels: major

#1362 Update stable15 to new docs
  appinfo/info.xml
  templates/admin.php
Labels: Skip-Changelog

#1368 Release 16.0.0-beta1
  CHANGELOG.md
  appinfo/info.xml
Labels: release

#1370 fix broken link
  templates/admin.php
Labels: Skip-Changelog, backport-request

#1371 backport link fix
  templates/admin.php
Labels: Skip-Changelog

#1373 add more meta data to docs
  mkdocs.yml
Labels: Skip-Changelog

#1372 fix missing "
  templates/admin.php
Labels: Skip-Changelog

#1339 db: no longer order by `items.last_modified`
  CHANGELOG.md
  lib/Db/ItemMapperV2.php
  tests/Unit/Db/ItemMapperAfterTest.php
  tests/Unit/Db/ItemMapperTest.php
Labels: 3. to review, API
