Repository nextcloud/news, pull requests merged in 2021-02, with the labels that each got.

#1096 fix item purger for PostgreSQL
  CHANGELOG.md
  lib/Db/ItemMapperV2.php
  lib/Db/NewsMapperV2.php
Labels: API, bug

#1110 fix articlesPerUpdate alias
  CHANGELOG.md
  lib/Db/ItemMapperV2.php
Labels: API, bug, patch

#1112 Composer: Remove unneeded files in releases
  CHANGELOG.md
  Makefile
  composer.json
  composer.lock
Labels: Skip-Changelog

#1114 .git dir not allowed by App Store
  Makefile
Labels: Skip-Changelog

#1119 Cleanup bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Skip-Changelog

#1123 fix result ordering for purging query
  CHANGELOG.md
  lib/Db/ItemMapperV2.php
Labels: bug, patch

#1128 Actions: Upload coverage on main branch
  .github/workflows/api-integration-tests.yml
  .github/workflows/api-php-static-code-check.yml
  .github/workflows/api-php-tests.yml
  .github/workflows/build-release.yml
  .github/workflows/frontend-nodejs-tests.yml
  .github/workflows/post-merge-tasks.yml
  .github/workflows/release-drafter.yml
Labels: Skip-Changelog

#1132 use 'github.workspace' in release action
  .github/workflows/build-release.yml
Labels: Skip-Changelog

#1134 Release: revert back to cd
  .github/workflows/build-release.yml
Labels: Skip-Changelog, enhancement

#1135 Release 15.3.1-rc2
  CHANGELOG.md
  appinfo/info.xml
Labels: 4. to release

#1136 Actions: Setup app before release
  .github/workflows/build-release.yml
Labels: Skip-Changelog

#1153 fix refetching of purged articles
  CHANGELOG.md
  lib/Db/ItemMapperV2.php
Labels: bug, patch

#1155 improve file_from_env script
  bin/tools/file_from_env.php
Labels: Skip-Changelog, enhancement

#1156 Fix release flow
  .github/workflows/build-release.yml
Labels: Skip-Changelog

#1163 remove stable20 from psalm run
  .github/workflows/api-php-static-code-check.yml
Labels: API, Skip-Changelog

#1169 Actions: force enable app on pre-release versions
  .github/workflows/api-integration-tests.yml
Labels: Skip-Changelog

#1056 Remove V1 item API
  CHANGELOG.md
  lib/AppInfo/Application.php
  lib/Command/Config/FolderDelete.php
  lib/Controller/ApiController.php
  lib/Controller/FeedApiController.php
  lib/Controller/FeedController.php
  lib/Controller/FolderApiController.php
  lib/Controller/FolderController.php
  lib/Controller/ItemApiController.php
  lib/Controller/ItemController.php
  lib/Controller/PageController.php
  lib/Db/FeedMapperV2.php
  lib/Db/FeedType.php
  lib/Db/FolderMapperV2.php
  lib/Db/ItemMapper.php
  lib/Db/ItemMapperV2.php
  lib/Db/MapperFactory.php
  lib/Db/Mysql/ItemMapper.php
  lib/DependencyInjection/IFactory.php
  lib/Explore/Exceptions/RecommendedSiteNotFoundException.php
  lib/Explore/RecommendedSiteNotFoundException.php
  lib/Explore/RecommendedSites.php
  lib/Service/Exceptions/ServiceConflictException.php
  lib/Service/Exceptions/ServiceException.php
  lib/Service/Exceptions/ServiceNotFoundException.php
  lib/Service/Exceptions/ServiceValidationException.php
  lib/Service/FeedServiceV2.php
  lib/Service/FolderServiceV2.php
  lib/Service/ItemService.php
  lib/Service/ItemServiceV2.php
  lib/Service/Service.php
  phpunit.xml
  tests/Unit/Command/FolderDeleteTest.php
  tests/Unit/Controller/FeedApiControllerTest.php
  tests/Unit/Controller/FeedControllerTest.php
  tests/Unit/Controller/FolderApiControllerTest.php
  tests/Unit/Controller/FolderControllerTest.php
  tests/Unit/Controller/ItemApiControllerTest.php
  tests/Unit/Controller/ItemControllerTest.php
  tests/Unit/Controller/PageControllerTest.php
  tests/Unit/Db/FeedMapperTest.php
  tests/Unit/Db/FolderMapperTest.php
  tests/Unit/Db/ItemMapperTest.php
  tests/Unit/Db/MapperFactoryTest.php
  tests/Unit/Db/MapperTestUtility.php
  tests/Unit/Service/FeedServiceTest.php
  tests/Unit/Service/FolderServiceTest.php
  tests/Unit/Service/ItemServiceTest.php
  tests/Unit/Service/ServiceTest.php
  tests/psalm-baseline.xml
Labels: 4. to release, API, enhancement, minor

#1170 update sorting column
  lib/Db/ItemMapperV2.php
  tests/Unit/Db/ItemMapperTest.php
Labels: Skip-Changelog

#1164 FeedFetcher: Use feeds logo instead of the favicon
  .github/workflows/api-integration-tests.yml
  CHANGELOG.md
  lib/Command/ShowFeed.php
  lib/Fetcher/FeedFetcher.php
  lib/Fetcher/Fetcher.php
  lib/Fetcher/IFeedFetcher.php
  lib/Service/FeedServiceV2.php
  tests/Unit/Command/ShowFeedTest.php
  tests/Unit/Fetcher/FeedFetcherTest.php
Labels: 3. to review, API, enhancement

#1162 remove unused lastModified from feed fetcher
  composer.lock
  lib/Command/ShowFeed.php
  lib/Fetcher/FeedFetcher.php
  lib/Fetcher/Fetcher.php
  lib/Fetcher/IFeedFetcher.php
  lib/Service/FeedServiceV2.php
  tests/Unit/Command/ShowFeedTest.php
  tests/Unit/Fetcher/FeedFetcherTest.php
  tests/Unit/Fetcher/FetcherTest.php
Labels: API, Skip-Changelog, enhancement

#1182 Actions: remove psalm
  .github/workflows/api-php-static-code-check.yml
  composer.json
Labels: Skip-Changelog

#1183 Static Code analysis part 2
  .github/workflows/api-php-static-code-check.yml
  .github/workflows/api-php-tests.yml
  composer.json
  composer.lock
  psalm.xml
  tests/psalm-autoload.php
  tests/psalm-baseline.xml
Labels: Skip-Changelog

#1148 Fix id sorting bug
  CHANGELOG.md
  js/controller/ContentController.js
  js/tests/unit/controller/ContentControllerSpec.js
  templates/part.content.php
Labels: enhancement, frontend

#1196 Actions: Fix codecov commit finding
  .github/workflows/api-php-tests.yml
  AUTHORS.md
Labels: Skip-Changelog

#1197 Release 15.4.0-beta1
  CHANGELOG.md
  appinfo/info.xml
Labels: 4. to release

#1201 DB: Fix offset quotes
  CHANGELOG.md
  lib/Db/ItemMapperV2.php
  tests/Unit/Db/ItemMapperPaginatedTest.php
Labels: patch
