Repository nextcloud/news, pull requests merged in 2021-04, with the labels that each got.

#1287 Search: Fix and test folder search
  AUTHORS.md
  CHANGELOG.md
  lib/Search/FolderSearchProvider.php
  tests/Unit/Search/FolderSearchProviderTest.php
Labels: backport-request

#1289 Search: Fix and test folder search
  AUTHORS.md
  CHANGELOG.md
  lib/Search/FolderSearchProvider.php
  tests/Unit/Search/FolderSearchProviderTest.php
Labels: Skip-Changelog

#1292 Backport/1291
  AUTHORS.md
  CHANGELOG.md
  lib/Db/ItemMapperV2.php
  tests/Unit/Db/ItemMapperPaginatedTest.php
  tests/Unit/Db/ItemMapperTest.php
Labels: Skip-Changelog

#1294 Release 15.4.0-rc1
  appinfo/info.xml
Labels: Skip-Changelog

#1300 delete key and crt after the last step
  .github/workflows/build-release.yml
Labels: Skip-Changelog, backport-request, bug, patch

#1302 Backport/1300
  .github/workflows/build-release.yml
Labels: Skip-Changelog, bug, patch
