Repository nextcloud/news, pull requests merged in 2022-10, with the labels that each got.

#1933 Release 18.3.0-beta1
  CHANGELOG.md
  appinfo/info.xml
Labels: 4. to release

#1934 fix wording to articles
  src/components/AdminSettings.vue
Labels: Skip-Changelog

#1938 Updating lint-eslint.yml workflow from template
  .github/workflows/lint-eslint.yml
Labels: dependencies, Skip-Changelog

#1947 add conditon to check for existing key and crt
  Makefile
Labels: Skip-Changelog

#1948 Release 18.3.0
  CHANGELOG.md
  appinfo/info.xml
Labels: 4. to release

#1950 Release 19.0.0-beta1
  .github/workflows/api-integration-tests.yml
  .github/workflows/api-php-static-code-check.yml
  .github/workflows/api-php-tests.yml
  .github/workflows/build-release.yml
  .github/workflows/post-merge-tasks.yml
  CHANGELOG.md
  appinfo/info.xml
Labels: 4. to release

#1955 Release 19.0.0-beta2
  CHANGELOG.md
  appinfo/info.xml
Labels: 4. to release

#1957 Use app password, change setup method
  .github/workflows/api-integration-tests.yml
  tests/api/feeds.bats
  tests/api/folders.bats
  tests/api/helpers/settings.bash
  tests/api/items.bats
  tests/test_helper/feeds/Nextcloud.rss
  tests/test_helper/feeds/heise.xml
Labels: Skip-Changelog
