Repository nextcloud/news, pull requests merged in 2022-08, with the labels that each got.

#1859 Release 18.1.1
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#1871 fixup for #1861
  lib/Utility/OPMLExporter.php
Labels: Skip-Changelog

#1874 try to speedup the api testing by hosting the feeds locally
  .github/workflows/api-integration-tests.yml
  tests/api/feeds.bats
  tests/api/folders.bats
  tests/api/helpers/settings.bash
  tests/api/items.bats
  tests/command/feeds.bats
  tests/command/helpers/settings.bash
  tests/test_helper/feeds/Nextcloud.rss
  tests/test_helper/feeds/heise.xml
  tests/test_helper/feeds/no_guid_feed.xml
Labels: Skip-Changelog

#1880 Port admin settings to vue
  .eslintrc.js
  .github/workflows/lint-eslint.yml
  CHANGELOG.md
  Makefile
  babel.config.js
  css/explore.css
  css/explore.scss
  css/mobile.css
  js/gulpfile.js
  lib/Controller/AdminController.php
  lib/Settings/AdminSettings.php
  package-lock.json
  package.json
  src/components/AdminSettings.vue
  src/main-admin.js
  stylelint.config.js
  templates/admin.php
  tests/Unit/Controller/AdminControllerTest.php
  webpack.config.js
Labels: enhancement, 3. to review, Technical debt, frontend

#1891 fix readAll method fails due to missing parameter
  lib/Db/ItemMapperV2.php
  tests/Unit/Db/ItemMapperTest.php
Labels: Skip-Changelog

#1894 fix truncated string for Transifex
  src/components/AdminSettings.vue
Labels: Skip-Changelog
