Repository nextcloud/news, pull requests merged in 2024-01, with the labels that each got.

#2528 fix: ESLint errors
  src/components/AdminSettings.vue
  src/components/ContentTemplate.vue
  src/components/ShareItem.vue
  src/components/feed-display/FeedItemDisplay.vue
  src/components/feed-display/FeedItemRow.vue
  src/dataservices/feed.service.ts
  src/dataservices/folder.service.ts
  src/main.js
  src/store/item.ts
Labels: Skip-Changelog

#2549 Update npm and node engines versions
  package.json
Labels: dependencies

#2553 FolderRead: add type declarations
  lib/Command/Debug/FolderRead.php
Labels: 3. to review, Technical debt, Skip-Changelog
