Repository nextcloud/news, pull requests merged in 2024-11, with the labels that each got.

#2861 update nextcloud-vue v8
  package-lock.json
  package.json
  src/components/AdminSettings.vue
  src/components/ContentTemplate.vue
  src/components/Sidebar.vue
  src/components/SidebarFeedLinkActions.vue
  tests/javascript/helpers/unist-stub.js
  tests/javascript/unit/components/AdminSettings.spec.ts
Labels: dependencies, frontend, Skip-Changelog, major

#2884 deps: fix npm audit
  package-lock.json
Labels: dependencies, Skip-Changelog

#2894 never tag a release as nightly in the appstore
  .github/workflows/build-release.yml
Labels: Skip-Changelog

#2914 dev-deps: remove unused devDependencies
  package-lock.json
  package.json
Labels: dependencies, frontend, Skip-Changelog

#2933 dev-deps: update @typescript-eslint to 8.16.0 with support added for typescript 5.7
  package-lock.json
  package.json
Labels: dependencies, frontend, Skip-Changelog, minor

#2942 [Actions] Frontend tests do not try to install firefox
  .github/workflows/frontend-nodejs-tests.yml
Labels: Skip-Changelog
