Repository nextcloud/news, pull requests merged in 2025-01, with the labels that each got.

#3018 Create lint-info-xml.yml
  .github/workflows/lint-info-xml.yml
Labels: Skip-Changelog

#3025 npm audit fix
  package-lock.json
Labels: dependencies, frontend, Skip-Changelog

#3036 feat: show error message from opml import in web-ui
  CHANGELOG.md
  lib/Controller/ImportController.php
  src/components/Sidebar.vue
Labels: API, frontend

#3040 show url directly in log message
  lib/Service/FeedServiceV2.php
Labels: Skip-Changelog

#3041 docs: add documentation for feed options and settings for the web-ui
  docs/user.md
Labels: Skip-Changelog, documentation

#3078 Fix build pipeline
  Makefile
Labels: Skip-Changelog
