Repository nextcloud/news, pull requests merged in 2025-05, with the labels that each got.

#3155 fix: item list not updated by automatic or manual refresh
  src/components/feed-display/FeedItemDisplayList.vue
  src/components/feed-display/VirtualScroll.vue
Labels: frontend, Skip-Changelog

#3159 refactor: use html5 history mode
  CHANGELOG.md
  appinfo/routes.php
  src/routes/index.ts
Labels: 3. to review, API, frontend

#3168 fix: possible race conditions when switching routes
  CHANGELOG.md
  src/App.vue
  src/components/feed-display/FeedItemDisplayList.vue
  src/components/routes/All.vue
  src/components/routes/Feed.vue
  src/components/routes/Folder.vue
  src/components/routes/Starred.vue
  src/components/routes/Unread.vue
  src/dataservices/item.service.ts
  src/store/feed.ts
  src/store/item.ts
  tests/javascript/unit/components/feed-display/FeedItemDisplayList.spec.ts
  tests/javascript/unit/store/item.spec.ts
Labels: frontend

#3169 feat: show feed info table during opml import
  CHANGELOG.md
  src/components/Sidebar.vue
  src/components/modals/FeedInfoTable.vue
Labels: frontend

#3187 fix: stylelint warnings from update @nextcloud/stylelint-config 3.1.0
  src/App.vue
  src/components/Sidebar.vue
  src/components/feed-display/FeedItemDisplay.vue
  src/components/feed-display/FeedItemDisplayList.vue
  src/components/modals/FeedInfoTable.vue
  src/components/routes/All.vue
  src/components/routes/Explore.vue
  src/components/routes/Feed.vue
  src/components/routes/Folder.vue
  src/components/routes/Starred.vue
  src/components/routes/Unread.vue
Labels: 3. to review, frontend, Skip-Changelog

#3186 feat: show intro and date if enough space in compact mode
  CHANGELOG.md
  src/components/feed-display/FeedItemRow.vue
Labels: 3. to review, frontend

#3194 fix: close action menu before renaming or deleting navigation item
  src/components/Sidebar.vue
  src/components/SidebarFeedLinkActions.vue
Labels: 3. to review, frontend, Skip-Changelog

#3188 Release 26.0.0
  CHANGELOG.md
  appinfo/info.xml
Labels: 4. to release
