Repository nextcloud/news, pull requests merged in 2025-09, with the labels that each got.

#3311 deps: update vite to 7.1.5 and @nextcloud/vite-config to 2.5.0
  package-lock.json
  package.json
Labels: dependencies, frontend, Skip-Changelog

#3316 feat: add option to enable/disable sync of a feed
  CHANGELOG.md
  lib/Controller/FeedController.php
  src/components/SidebarFeedLinkActions.vue
  src/components/modals/FeedInfoTable.vue
  src/dataservices/feed.service.ts
  src/store/feed.ts
  src/types/Feed.ts
  tests/Unit/Controller/FeedControllerTest.php
Labels: enhancement, 3. to review, API, frontend

#3332 fix: update package lists before installing httpie
  .github/workflows/api-integration-tests.yml
  .github/workflows/updater-test.yml
Labels: 3. to review, Skip-Changelog

#3333 update php packages
  composer.json
  composer.lock
Labels: Skip-Changelog
