Repository nextcloud/news, pull requests merged in 2025-08, with the labels that each got.

#3263 fix npm dependabot issues
  package.json
Labels: dependencies, frontend, Skip-Changelog

#3267 fix: Unread counter displays a huge number of unread posts
  CHANGELOG.md
  src/store/feed.ts
Labels: 3. to review, frontend

#3284 build: update node and npm engines versions
  package.json
Labels: dependencies, Skip-Changelog
